// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcQCkP_I2ot2571BTnmK-A_uYma94n_RE',
    appId: '1:168243316465:web:31b5a16cb0bcefa0c50b50',
    messagingSenderId: '168243316465',
    projectId: 'barzzy-24036',
    authDomain: 'barzzy-24036.firebaseapp.com',
    storageBucket: 'barzzy-24036.appspot.com',
    measurementId: 'G-NXSVJPHVC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB3Z9jc6LBl6-Yg0QsG8NgptC0_9MHx1A',
    appId: '1:168243316465:android:903d3e77f90ad61dc50b50',
    messagingSenderId: '168243316465',
    projectId: 'barzzy-24036',
    storageBucket: 'barzzy-24036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZvF6KW7x8_Cr3djGWPiG8fVkRdjVh3rw',
    appId: '1:168243316465:ios:887bafba4d3d1ed6c50b50',
    messagingSenderId: '168243316465',
    projectId: 'barzzy-24036',
    storageBucket: 'barzzy-24036.appspot.com',
    iosBundleId: 'com.example.barzzyApp9',
  );
}
